# Setup
name:         CodeSplanations
tagline:      coding (eventually) toward a better climate
locale:       "en"
author:       Trevor Clack

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
#Others
markdown: kramdown
kramdown:
        math_engine: katex
        math_engine_opts: {}

baseurl:      "/blog"
#BASE_PATH: https://Tclack88.com/blog
production_url: "http://tclack88.github.io/blog" # the base hostname & protocol for your site
github_username: Tclack88
description: This is a 'blog', sure, but mostly a place where I can describe in detail the code I've written provide, its origin story, lessons learned during the process, relative background information and perhaps a few anecdotes along the way.
email: Tclack88@gmail.com
portfolio_url: "http://tclack88.github.io"
linkedin_url: "https://www.linkedin.com/in/trevor-clack-774696184/"
