# Setup
name:         BeginnerMediate
tagline:      Not a beginner — Not a comfortable intermediate — and certainly never done
locale:       "en"
author:       Trevor Clack

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
#Others
markdown: kramdown
kramdown:
        math_engine: katex

baseurl:      "/blog"
#BASE_PATH: https://Tclack88.com/blog
production_url: "http://tclack88.github.io/blog" # the base hostname & protocol for your site
github_username: Tclack88
description: This is a 'blog', sure, but mostly a place where I can describe in detail the code I've written provide, its origin story, lessons learned during the process, relative background information and perhaps a few anecdotes along the way. \
  I feel like I usually exist somewhere between beginner and intermediate with most things I do, thus the name.
email: Tclack88@gmail.com
portfolio_url: "http://tclack88.github.io"
linkedin_url: "https://www.linkedin.com/in/trevor-clack-774696184/"


# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
#staticman_url: https://staticman-tclack88githubio.herokuapp.com/v2/entry/${github-username}/${blog-repo}/master/comments
staticman_url: https://staticman-tclack88githubio.herokuapp.com/v2/entry/tclack88/blog/gh-pages/comments

comments: true

reCaptcha:
  enabled: true
  siteKey: 6LfQhv0UAAAAAEXvamf3hT6PirYnBIozTF9n4o3u
  secret: dSFMZz41qsItaB2s/f0XZJryNmgeav0bt5Rlt+uJGwPDiw3zke0zvNb1mFaPw2AWdq6TgTRPlfjbI2YEmRSK2NmNSaZR3rfKj7gPRZkvck6gDmEi1sQ7XGMx+R/H8/qXqKeQWyWsvVQaGRzlWXHKPCk6yokOJ4dASyNwTC0D1ap06igdvGEGsAlDdiLL+xJBrhbS03gOR0HIgUY9cxtdtZqKe8nmTlEqVxjSOz7eKa/sCWFfk0woBoGLiSZMUw+12P3tDXrJxjO4oI4b/VpYyIdzrTL92GHVYjegqq1xjzVPt6PKncJFDQB8pBXnoD5tO3RQrnbdJP9dty7bDbhULSmhLRm6NuC6tBIz8wifuRVT8r/3AzM3VO5nuitLJt/Omj9nki7b4KOKoDUT+Mn9NwNzWqzehZkgVam8KcC3E05xychCjA11tkZR9JBIB1jKSaW2jKEJWF6tSXE7rKwZx0/3/Ien9C0J9NIr3kvh86VQfCWfmUYxmR1/XD2hlsMdm+WjtCfuMIpbsKvMCMkZeiemrTA9cz08QTZWJYC8jxwRQv8e+OyuFMA12o/lZbq2ZUx8kNQj/DTqBWOSXfMw6nVHkCumgEANzMXiktnFQw0Crk0Qg5wwYArAphGeRvxgdW0T/WBiBsOEmjLi9yYEIghkTggOQp+5xv22nxT01UA=
